import type { QuestionArchetype } from "./types";

export const SEED_ARCHETYPES: QuestionArchetype[] = [
  {
    id: "arch_workflow_trace",
    name: "Workflow Trace",
    dimension: "operations",
    depths: [1, 2, 3],
    purpose: "Understand step-by-step sequence, actors, handoffs, and triggers.",
    targetState: "Low workflow coverage where overall process flow is unmapped.",
    usefulWhen: "Trigger or high-level process is known, but the chronological sequence and responsible roles are unclear.",
    avoidWhen: "Step-by-step workflow has already been adequately mapped in previous turns.",
    desiredEvidenceCategories: ["trigger", "actor", "action", "handoff", "system", "outcome"],
    strategyGuidance:
      "Ask an open-ended, non-leading question requesting a chronological walkthrough from trigger to outcome. Do not suggest specific tools or bottlenecks.",
    lifecycle: "SEEDED",
    sampleCount: 0,
    avgEfficacyScore: 0.75,
    variance: 0,
    invalidationsCount: 0,
    discrepanciesCount: 0,
    lastUpdated: Date.now()
  },
  {
    id: "arch_exception_probe",
    name: "Exception & Breakdown Probe",
    dimension: "operations",
    depths: [3, 4, 5],
    purpose: "Map failure modes, manual workarounds, delays, and exceptions.",
    targetState: "Baseline workflow is established (ADEQUATE), but failure points and edge cases are unmapped.",
    usefulWhen: "The standard 'happy path' is known and we need to discover where manual intervention or friction occurs.",
    avoidWhen: "The baseline workflow has not yet been established at depth 1 or 2.",
    desiredEvidenceCategories: ["failure_mode", "delay", "manual_override", "exception_handling", "escalation"],
    strategyGuidance:
      "Ask neutrally about what happens when the process does not go smoothly or encounters exceptions. Avoid leading questions like 'Is X your biggest problem?'.",
    lifecycle: "SEEDED",
    sampleCount: 0,
    avgEfficacyScore: 0.78,
    variance: 0,
    invalidationsCount: 0,
    discrepanciesCount: 0,
    lastUpdated: Date.now()
  },
  {
    id: "arch_handoff_boundary",
    name: "Handoff & System Boundary Probe",
    dimension: "systems",
    depths: [2, 3, 4],
    purpose: "Trace how information and artifacts cross between systems, tools, or teams.",
    targetState: "Multiple systems or departments mentioned, but integration and data flow between them is unknown.",
    usefulWhen: "Two or more distinct platforms/teams are identified and we need to know whether data transfers are automated or manual.",
    avoidWhen: "Only a single standalone tool/actor is involved with no upstream or downstream handoffs.",
    desiredEvidenceCategories: ["data_transfer", "format_conversion", "manual_reentry", "notification", "sync_gap"],
    strategyGuidance:
      "Ask an open question about how information moves from one stage/tool to the next. Do not assume APIs or manual entry exist.",
    lifecycle: "SEEDED",
    sampleCount: 0,
    avgEfficacyScore: 0.8,
    variance: 0,
    invalidationsCount: 0,
    discrepanciesCount: 0,
    lastUpdated: Date.now()
  },
  {
    id: "arch_signal_verification",
    name: "Neutral Signal Verification",
    dimension: "business",
    depths: [1, 2, 3],
    purpose: "Neutrally verify public signals (scraped tech, job posts, reviews) against internal operational reality.",
    targetState: "A public signal exists but internal day-to-day adoption/reliance is unverified.",
    usefulWhen: "A specific tool or practice was detected in public research and needs neutral ground-truthing.",
    avoidWhen: "No prior signal exists, or when the tool has already been confirmed/invalidated.",
    desiredEvidenceCategories: ["tool_adoption", "active_usage", "abandoned_system", "alternative_solution"],
    strategyGuidance:
      "Ask neutrally: 'What role, if any, does [system/tool/practice] play in this area?'. NEVER assume the signal is active or critical.",
    lifecycle: "SEEDED",
    sampleCount: 0,
    avgEfficacyScore: 0.76,
    variance: 0,
    invalidationsCount: 0,
    discrepanciesCount: 0,
    lastUpdated: Date.now()
  },
  {
    id: "arch_volume_cadence",
    name: "Operational Volume & Cadence Probe",
    dimension: "data",
    depths: [2, 3, 4],
    purpose: "Establish transaction volume, frequency, and operational scale.",
    targetState: "Workflow is understood, but frequency, batch size, or throughput is unquantified.",
    usefulWhen: "The process is mapped and we need to understand whether this happens once a month or 500 times a day.",
    avoidWhen: "The nature of the work is still fundamentally unknown.",
    desiredEvidenceCategories: ["frequency", "batch_size", "throughput", "time_spent", "seasonal_variance"],
    strategyGuidance:
      "Ask neutrally about how often this occurs or roughly what volume passes through, without demanding precise metrics.",
    lifecycle: "SEEDED",
    sampleCount: 0,
    avgEfficacyScore: 0.74,
    variance: 0,
    invalidationsCount: 0,
    discrepanciesCount: 0,
    lastUpdated: Date.now()
  },
  {
    id: "arch_responsibility_role",
    name: "Role & Responsibility Allocation",
    dimension: "people",
    depths: [1, 2, 3],
    purpose: "Clarify who performs each part of the work, skill requirements, and team constraints.",
    targetState: "Work is described broadly, but specific roles, team size, or allocation of tasks is unclear.",
    usefulWhen: "Understanding the division of labor, key person dependencies, or internal vs. external execution.",
    avoidWhen: "Team structure and task ownership are already explicitly documented.",
    desiredEvidenceCategories: ["role_allocation", "team_size", "skill_gap", "key_person_dependency"],
    strategyGuidance:
      "Ask who on the team typically handles this work and how responsibilities are distributed, keeping it conversational.",
    lifecycle: "SEEDED",
    sampleCount: 0,
    avgEfficacyScore: 0.75,
    variance: 0,
    invalidationsCount: 0,
    discrepanciesCount: 0,
    lastUpdated: Date.now()
  }
];
